---
- name: install nginx
  apt: name=nginx state=latest
  when: ansible_os_family == "Debian"

- name: install nginx
  yum: name=nginx state=latest
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Copy config file
  template:
     src: default
     dest: /etc/nginx/sites-enabled/default
  notify: restart nginx                 
