---

- name: drupal-setup
  command: wget https://ftp.drupal.org/files/projects/drupal-8.6.2.tar.gz

- name: drupal-extract
  command: tar -zxf drupal-8.6.2.tar.gz -C /var/www/html

- name: drupal-directory
  command: mv /var/www/html/drupal-8.6.2 /var/www/html/drupal

- name: Update permissions of sites directory
  file: path=/var/www/html/drupal/sites/ mode=777

- name: Create settings.php
  command: cp /var/www/html/drupal/sites/default/default.settings.php /var/www/html/drupal/sites/default/settings.php

- name: Create services.yml
  command: cp /var/www/html/drupal/sites/default/default.services.yml /var/www/html/drupal/sites/default/services.yml

- name: Update permissions of settings.php
  file: path=/var/www/html/drupal/sites/default/settings.php mode=777

- name: Update permissions of services.yml
  file: path=/var/www/html/drupal/sites/default/services.yml mode=777

- name: Update permissions of files directory
  file: >
    path=/var/www/html/drupal/sites/default/files
    mode=777
    state=directory
    recurse=yes
